export const items = [
  {
    id: 1,
    category: "apparel",
    name: "تی‌شرت ورزشی آبی",
    description:
      "تی‌شرت ورزشی با کیفیت بالا و جنس تنفسی مناسب برای دویدن و تمرینات هوازی",
    price: 150000,
    image: "/images/store/product-1.webp",
    material: "100% پلی‌استر میکروفیبر با تکنولوژی Dry-Fit",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    color: "آبی اقیانوسی",
    weight: "180g",
    care: "شستشو با آب سرد، خشک کردن در سایه، اتوکشی با دمای پایین",
    inStock: true,
    rating: 4.5,
    reviews: 128,
    features: ["جذب رطوبت", "ضد بو", "درزهای صاف", "یقه گرد"],
    brand: "اسپورت لاین",
    madeIn: "ترکیه",
    season: "چهار فصل",
    gender: "مردانه",
    warranty: "6 ماه",
  },
  {
    id: 2,
    category: "apparel",
    name: "تی‌شرت ورزشی سیاه",
    description: "تی‌شرت ورزشی سیاه با طراحی مدرن و مناسب برای بدنسازی",
    price: 160000,
    image: "/images/store/product-2.webp",
    material: "85% پلی‌استر، 15% الاستان (اسپاندکس) با قابلیت کشسانی بالا",
    sizes: ["S", "M", "L", "XL", "XXL"],
    color: "سیاه مات",
    weight: "185g",
    care: "شستشو با آب گرم تا ۳۰ درجه، خشک کردن در سایه، عدم استفاده از سفیدکننده",
    inStock: true,
    rating: 4.8,
    reviews: 256,
    features: ["۴ جهت کشسانی", "دوخت تقویت شده", "یقه V شکل", "آرم بازتابنده"],
    brand: "پرفورمنس",
    madeIn: "ایران",
    season: "بهار و تابستان",
    gender: "مردانه",
    warranty: "۱۲ ماه",
  },
  {
    id: 3,
    category: "apparel",
    name: "تی‌شرت ورزشی قرمز",
    description: "تی‌شرت ورزشی قرمز رنگ شاد و جاذب توجه برای دوچرخه‌سواری",
    price: 155000,
    image: "/images/store/product-3.jpg",
    material: "100% پلی‌استر با الیاف خنک‌کننده",
    sizes: ["XS", "S", "M", "L", "XL"],
    color: "قرمز آتشین",
    weight: "180g",
    care: "شستشو در آب سرد تا ۳۰ درجه، خشک کردن در سایه، اتو با دمای متوسط",
    inStock: true,
    rating: 4.3,
    reviews: 95,
    features: ["محافظ UV", "تهویه مطبوع", "جیب زیپ‌دار پشت", "درزهای مسطح"],
    brand: "اسپورت لاین",
    madeIn: "چین",
    season: "تابستان",
    gender: "مردانه",
    warranty: "۳ ماه",
  },
  {
    id: 4,
    category: "apparel",
    name: "تی‌شرت ورزشی سفید",
    description: "تی‌شرت ورزشی سفید کلاسیک و چند منظوره برای تمام ورزش‌ها",
    price: 145000,
    image: "/images/store/product-4.jpg",
    material: "100% پلی‌استر با تکنولوژی ضد باکتری",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    color: "سفید برفی",
    weight: "175g",
    care: "شستشو با آب سرد، استفاده از سفید‌کننده خفیف، خشک کردن طبیعی",
    inStock: true,
    rating: 4.6,
    reviews: 189,
    features: ["ضخامت استاندارد", "مناسب چاپ", "یقه گرد کلاسیک", "آستین کوتاه"],
    brand: "بیسیک اکتیو",
    madeIn: "ترکیه",
    season: "چهار فصل",
    gender: "زنانه و مردانه",
    warranty: "۶ ماه",
  },
  {
    id: 5,
    category: "apparel",
    name: "تی‌شرت ورزشی خاکستری",
    description: "تی‌شرت ورزشی خاکستری مناسب برای تمام فصل‌ها با طراحی مینیمال",
    price: 150000,
    image: "/images/store/product-5.jpg",
    material: "88% پلی‌استر، 12% الاستان (اسپاندکس)",
    sizes: ["S", "M", "L", "XL", "XXL"],
    color: "خاکستری طوسی",
    weight: "182g",
    care: "شستشو با آب سرد، خشک کردن طبیعی، اتو با دمای پایین",
    inStock: true,
    rating: 4.4,
    reviews: 142,
    features: ["نرم و لطیف", "کشسان", "مقاوم در برابر چروک", "تهویه مناسب"],
    brand: "پرفورمنس",
    madeIn: "ایران",
    season: "پاییز و زمستان",
    gender: "مردانه",
    warranty: "۶ ماه",
  },
  {
    id: 6,
    category: "apparel",
    name: "تی‌شرت ورزشی سبز",
    description: "تی‌شرت ورزشی سبز با قابلیت جذب رطوبت بالا و خشک شدن سریع",
    price: 155000,
    image: "/images/store/product-6.jpg",
    material: "100% پلی‌استر بازیافتی (سازگار با محیط زیست)",
    sizes: ["XS", "S", "M", "L", "XL"],
    color: "سبز زمردی",
    weight: "178g",
    care: "شستشو در آب سرد، خشک کردن در هوای آزاد، شستشو با لباس‌های همرنگ",
    inStock: false,
    rating: 4.7,
    reviews: 203,
    features: ["الیاف بازیافتی", "کربن خنثی", "بسته‌بندی سبز", "ضد تعریق"],
    brand: "اکو اسپورت",
    madeIn: "آلمان",
    season: "چهار فصل",
    gender: "مردانه",
    warranty: "۱۲ ماه",
  },
  {
    id: 7,
    category: "nutrition",
    name: "پروتئین وی (Whey Protein)",
    description:
      "پروتئین وی خالص با غلظت بالا برای رشد عضلات و بازیابی سریع پس از تمرین",
    price: 450000,
    image: "/images/store/supplement-1.webp",
    servingSize: "۳۰ گرم (یک پیمانه)",
    servingsPerPackage: 30,
    protein: "۲۵ گرم",
    calories: 120,
    ingredients: [
      "پروتئین وی کنسانتره",
      "لسیتین سویا",
      "طعم‌دهنده طبیعی",
      "سوکرالوز",
    ],
    flavor: "شکلات فاج",
    expiryMonths: 12,
    inStock: true,
    rating: 4.9,
    reviews: 512,
    usage: "یک پیمانه نیم ساعت پس از تمرین یا صبح‌ها",
    aminoProfile: [
      "لوسین ۲.۵ گرم",
      "ایزولوسین ۱.۴ گرم",
      "والین ۱.۳ گرم",
      "گلوتامین ۴ گرم",
    ],
    allergen: "حاوی شیر و سویا",
    storage: "در جای خشک و خنک نگهداری شود",
    brand: "نوتریشن پلاس",
    country: "آمریکا",
    suitable: "ورزشکاران و بدنسازان",
  },
  {
    id: 8,
    category: "nutrition",
    name: "کراتین مونوهیدرات",
    description:
      "کراتین مونوهیدرات میکرونایز شده آلمانی برای افزایش قدرت، حجم و تحمل عضلانی",
    price: 280000,
    image: "/images/store/supplement-2.webp",
    servingSize: "۵ گرم (یک قاشق)",
    servingsPerPackage: 60,
    creatine: "۵ گرم کراتین خالص",
    calories: 0,
    ingredients: ["کراتین مونوهیدرات ۹۹.۹% خالص (تولید آلمان)"],
    flavor: "بدون طعم",
    expiryMonths: 24,
    inStock: true,
    rating: 4.8,
    reviews: 389,
    usage: "۵ گرم قبل یا بعد تمرین، همراه با آب یا آبمیوه",
    loadingPhase: "۲۰ گرم روزانه در هفته اول (اختیاری)",
    solubility: "حلالیت بالا (میکرونایز شده)",
    storage: "دور از رطوبت و نور مستقیم",
    brand: "پرفورمنس لب",
    country: "آلمان",
    suitable: "بدنسازان و ورزشکاران قدرتی",
  },
  {
    id: 9,
    category: "nutrition",
    name: "BCAA (آمینواسیدهای شاخه‌دار)",
    description:
      "BCAA با نسبت استاندارد ۲:۱:۱ برای کاهش خستگی عضلانی و افزایش ریکاوری",
    price: 320000,
    image: "/images/store/supplement-3.webp",
    servingSize: "۱۰ گرم (دو پیمانه)",
    servingsPerPackage: 40,
    bcaa: "۱۰ گرم (لوسین ۵۰۰۰mg، ایزولوسین ۲۵۰۰mg، والین ۲۵۰۰mg)",
    calories: 40,
    ingredients: ["لوسین", "ایزولوسین", "والین", "الکترولیت‌ها", "اسید سیتریک"],
    flavor: "انبه و هلو",
    expiryMonths: 18,
    inStock: true,
    rating: 4.6,
    reviews: 276,
    usage: "۱۰ گرم در حین تمرین یا بلافاصله پس از آن",
    mixability: "حلالیت عالی در آب سرد",
    caffeine: "فاقد کافئین",
    storage: "پس از باز شدن در یخچال نگهداری شود",
    brand: "نوتریشن پلاس",
    country: "آمریکا",
    suitable: "تمام ورزشکاران",
  },
  {
    id: 10,
    category: "nutrition",
    name: "مولتی‌ویتامین مینرال",
    description:
      "قرص مولتی‌ویتامین کامل با ۲۳ ویتامین و ماده معدنی برای سلامت عمومی و تقویت سیستم ایمنی",
    price: 200000,
    image: "/images/store/supplement-4.webp",
    servingSize: "۱ قرص",
    servingsPerPackage: 60,
    vitamins: [
      "A (۱۰۰۰IU)",
      "B1 (۱.۵mg)",
      "B2 (۱.۷mg)",
      "B3 (۲۰mg)",
      "B5 (۱۰mg)",
      "B6 (۲mg)",
      "B12 (۶mcg)",
      "C (۶۰mg)",
      "D3 (۸۰۰IU)",
      "E (۱۵mg)",
    ],
    minerals: [
      "روی (۱۵mg)",
      "منیزیم (۱۰۰mg)",
      "کلسیم (۲۰۰mg)",
      "سلنیوم (۵۵mcg)",
    ],
    calories: 5,
    ingredients: ["ویتامین‌ها و مواد معدنی به شکل سیترات و گلوکونات"],
    flavor: "طبیعی",
    expiryMonths: 36,
    inStock: true,
    rating: 4.5,
    reviews: 198,
    usage: "روزانه یک قرص بعد از غذا",
    sideEffects: "در صورت مصرف زیاد ممکن است باعث تغییر رنگ ادرار شود",
    storage: "دور از کودکان، در جای خشک و خنک",
    brand: "ویتالایف",
    country: "کانادا",
    suitable: "عمومی",
  },
  {
    id: 11,
    category: "nutrition",
    name: "اسپیرولینا ارگانیک",
    description:
      "اسپیرولینای طبیعی ارگانیک غنی از پروتئین، آهن و آنتی‌اکسیدان‌ها",
    price: 250000,
    image: "/images/store/supplement-5.webp",
    servingSize: "۳ گرم (۶ قرص)",
    servingsPerPackage: 60,
    protein: "۲.۷ گرم",
    calories: 10,
    ingredients: ["اسپیرولینا پلاتنسیس ۱۰۰% خالص ارگانیک"],
    flavor: "طعم طبیعی دریایی",
    expiryMonths: 24,
    inStock: true,
    rating: 4.7,
    reviews: 234,
    features: ["کشت در آب‌های پاک", "بدون GMO", "گیاه‌خواری", "بدون گلوتن"],
    usage: "روزانه ۶ قرص همراه با آب، نیم ساعت قبل از غذا",
    iron: "۲ میلی‌گرم",
    chlorophyll: "۵۰ میلی‌گرم",
    storage: "در جای خشک و خنک، دور از نور",
    brand: "اکو ویتال",
    country: "هند",
    suitable: "گیاه‌خواران، ورزشکاران استقامتی",
  },
  {
    id: 12,
    category: "nutrition",
    name: "آمینو اسید کامل (EAA)",
    description:
      "آمینو اسیدهای ضروری (EAA) شامل ۹ آمینو اسید ضروری برای بازیابی عضلات",
    price: 380000,
    image: "/images/store/supplement-6.avif",
    servingSize: "۸ گرم",
    servingsPerPackage: 50,
    aminoAcids:
      "۹ آمینو اسید اساسی (هیستیدین، ایزولوسین، لوسین، لیزین، متیونین، فنیل‌آلانین، ترئونین، تریپتوفان، والین)",
    calories: 32,
    ingredients: ["آمینواسیدهای ضروری", "الکترولیت‌ها", "استویا"],
    flavor: "نوار تمشک و لیمو",
    expiryMonths: 18,
    inStock: true,
    rating: 4.6,
    reviews: 267,
    usage: "۸ گرم در حین تمرین حل شده در ۵۰۰ میلی‌لیتر آب",
    vegan: "مناسب گیاه‌خواران",
    keto: "مناسب رژیم کتوژنیک",
    storage: "در جای خنک و خشک",
    brand: "پرفورمنس لب",
    country: "آمریکا",
    suitable: "ورزشکاران حرفه‌ای و بدنسازان",
  },
  {
    id: 13,
    category: "equipment",
    name: "دمبل ۱۰ کیلوگرمی (جفت)",
    description:
      "دمبل ۱۰ کیلوگرمی فولادی با روکش لاستیک برای تمرین شروع‌کنندگان",
    price: 350000,
    image: "/images/store/dumbbell-1.avif",
    weight: "۱۰ کیلوگرم (هر دمبل ۵ کیلوگرم)",
    material: "فولاد با پوشش لاستیکی (Rubber Coated)",
    diameter: "۳۲ میلی‌متر",
    length: "۲۵۰ میلی‌متر",
    grip: "دسته مات و ضد لغزش با شیارهای ارگونومیک",
    warranty: "۲ سال",
    inStock: true,
    rating: 4.8,
    reviews: 418,
    features: ["ضربه‌گیر", "بدون بو", "مناسب باشگاه خانگی", "ساختار یکپارچه"],
    shape: "شش‌ضلعی (Hex) ضد غلتش",
    application: "مناسب برای تمرینات قدرتی، بدنسازی و تناسب اندام",
    package: "جفت (۲ عدد)",
    brand: "پاور فیت",
    country: "چین",
  },
  {
    id: 14,
    category: "equipment",
    name: "دمبل ۲۰ کیلوگرمی (جفت)",
    description: "دمبل ۲۰ کیلوگرمی با روکش لاستیک برای تمرین میانی",
    price: 600000,
    image: "/images/store/dumbbell-2.webp",
    weight: "۲۰ کیلوگرم (هر دمبل ۱۰ کیلوگرم)",
    material: "فولاد با پوشش لاستیکی مقاوم",
    diameter: "۳۵ میلی‌متر",
    length: "۲۸۰ میلی‌متر",
    grip: "دسته مات با شیارهای ضد عرق",
    warranty: "۲ سال",
    inStock: true,
    rating: 4.9,
    reviews: 523,
    features: ["مقاوم در برابر ضربه", "مناسب استفاده روزانه", "سرهای شش‌ضلعی"],
    shape: "Hexagonal",
    application: "تمرینات قدرتی، بدنسازی، فیتنس",
    package: "جفت (۲ عدد)",
    brand: "پاور فیت",
    country: "چین",
  },
  {
    id: 15,
    category: "equipment",
    name: "دمبل ۳۰ کیلوگرمی (جفت)",
    description:
      "دمبل ۳۰ کیلوگرمی فولادی با روکش لاستیک ضخیم برای تمرین پیشرفته",
    price: 850000,
    image: "/images/store/dumbbell-4.jpg",
    weight: "۳۰ کیلوگرم (هر دمبل ۱۵ کیلوگرم)",
    material: "فولاد با پوشش لاستیکی چندلایه",
    diameter: "۳۸ میلی‌متر",
    length: "۳۱۰ میلی‌متر",
    grip: "دسته کروم با شیارهای عمیق ضد لغزش",
    warranty: "۳ سال",
    inStock: true,
    rating: 4.9,
    reviews: 389,
    features: [
      "پوشش لاستیک ۵ میلی‌متری",
      "تحمل وزن بالا",
      "ضد خوردگی",
      "تعادل عالی",
    ],
    shape: "Hexagonal با طراحی خاص",
    application: "مناسب برای تمرینات حرفه‌ای و پرقدرت",
    package: "جفت (۲ عدد)",
    brand: "پاور فیت پروفشنال",
    country: "چین",
  },
];
